In [1]:
import pandas as pd

In [32]:
data = (pd.read_csv("data.csv"))
data['datum'] = pd.to_datetime(data['datum'], errors='coerce')
data['rok'] = data['datum'].dt.year.astype('Int64')

data.head()
data.to_csv("data_rok.csv")

In [29]:
themes = [
    "Výzva k odstranění vozidla",
    "Změny rozpočtu",
    "nedoplatek",
    "Záměr pronájmu kanceláře",
    "Záměr pachtu částí pozemků",
    "Záměr prodeje pozemku"
]

for theme in themes:
    data[theme] = data['nazev'].str.contains(theme, case=False, na=False).astype(int)


grouped_data = data.groupby(['město', 'rok'])[themes].sum().reset_index()

grouped_data

,město,rok,Výzva k odstranění vozidla,Změny rozpočtu,nedoplatek,Záměr pronájmu kanceláře,Záměr pachtu částí pozemků,Záměr prodeje pozemku
0,Břecláv,2018,0,0,0,0,0,0
1,Břecláv,2020,0,0,0,0,2,0
2,Břecláv,2021,0,0,0,0,0,0
3,Břecláv,2022,0,0,0,1,0,1
4,Břecláv,2023,0,0,0,0,0,0
5,Břecláv,2024,0,0,0,0,0,3
6,Praha,2022,0,15,0,0,0,0
7,Praha,2023,0,24,0,0,0,0
8,Praha,2024,5,4,3,0,0,0

In [30]:
grouped_data.to_csv('group.csv')

In [36]:
data = pd.read_csv('data_rok.csv')

themes = [
    "Výzva k odstranění vozidla",
    "Změny rozpočtu",
    "nedoplatek",
    "Záměr pronájmu",
    'záměr prodeje',
    "Záměr pachtu částí pozemků"
]

result_data = pd.DataFrame()

for city in data['město'].unique():
    city_data = data[data['město'] == city].copy()
    
    for theme in themes:
        city_data[theme] = city_data['nazev'].str.contains(theme, case=False, na=False).astype(int)
    
    grouped_city_data = city_data.groupby(['město', 'rok'])[themes].sum().reset_index()
    
    result_data = pd.concat([result_data, grouped_city_data], ignore_index=True)
    
result_data

,město,rok,Výzva k odstranění vozidla,Změny rozpočtu,nedoplatek,Záměr pronájmu,záměr prodeje,Záměr pachtu částí pozemků
0,Praha,2022.0,0,15,0,0,0,0
1,Praha,2023.0,0,24,0,0,0,0
2,Praha,2024.0,5,4,3,0,0,0
3,Břecláv,2018.0,0,0,0,0,0,0
4,Břecláv,2020.0,0,0,0,0,0,2
5,Břecláv,2021.0,0,0,0,1,0,0
6,Břecláv,2022.0,0,0,0,5,1,0
7,Břecláv,2023.0,0,0,0,1,2,0
8,Břecláv,2024.0,0,0,0,1,9,0

In [38]:
cz = pd.read_csv('czech_rep.csv', usecols=['mesto', 'sirka', 'vyska', 'admin_name'])
cz['mesto'][0] = 'Praha'

C:\Users\Home\AppData\Local\Temp\ipykernel_13224\933222246.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  cz['mesto'][0] = 'Praha'
C:\Users\Home\AppData\Local\Temp\ipykernel_13224\933222246.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cz['mesto'][0] = 'Praha'

In [39]:
cz.to_csv('czech.csv')

In [59]:
data = pd.read_csv('all_data.csv',delimiter= ';')
data.head()

     město                                              nazev       datum
0  Bohumín      Oznámení SMOOK o rozpočtu pro rok 2023 - 2026  2021-12-07
1  Bohumín               Sdělení o závěrečném účtu města 2022  2023-04-13
2  Bohumín  Závěrečný účet Svazku měst a obcí okresu Karvi...  2023-07-03
3  Bohumín              Schválený rozpočet města pro rok 2024  2023-12-06
4  Bohumín  Oznámení SMOOK o schváleném střednědobém výhle...  2023-12-22

In [60]:
data['datum'] = pd.to_datetime(data['datum'], errors='coerce')
data['rok'] = data['datum'].dt.year.astype('Int64')

data.head()

     město                                              nazev      datum   rok
0  Bohumín      Oznámení SMOOK o rozpočtu pro rok 2023 - 2026 2021-12-07  2021
1  Bohumín               Sdělení o závěrečném účtu města 2022 2023-04-13  2023
2  Bohumín  Závěrečný účet Svazku měst a obcí okresu Karvi... 2023-07-03  2023
3  Bohumín              Schválený rozpočet města pro rok 2024 2023-12-06  2023
4  Bohumín  Oznámení SMOOK o schváleném střednědobém výhle... 2023-12-22  2023

In [62]:
from collections import Counter
import pandas as pd
import re

data['nazev'] = data['nazev'].str.lower()


def get_bigrams(text):
    
    words = re.findall(r'\b\w+\b', text)
    bigrams = zip(words, words[1:])
    return [' '.join(bigram) for bigram in bigrams]

all_text = ' '.join(data['nazev'].dropna())

all_bigrams = get_bigrams(all_text)

bigram_counts = Counter(all_bigrams)

bigram_counts_df = pd.DataFrame(bigram_counts.items(), columns=['Bigram', 'Count']).sort_values(by='Count', ascending=False)

print(bigram_counts_df.head(50))

                      Bigram  Count
1832            o poskytnutí   1725
1831               smlouva o   1443
88                oznámení o   1334
2220       poskytnutí dotace   1236
603           úpravy provozu    988
699         přechodné úpravy    847
154         veřejná vyhláška    824
698      stanovení přechodné    804
4975   veřejnoprávní smlouva    792
1836                dotace z    731
1837              z rozpočtu    676
1838          rozpočtu města    655
125                      k ú    581
1946                zákona č    401
2926              dle zákona    384
604               provozu na    380
4704                106 1999    378
4705                 1999 sb    377
4703                   č 106    374
234            obecné povahy    360
233          opatření obecné    360
188        dražební vyhláška    359
3545                     z s    355
423                   na rok    342
310                      v k    326
91         přerušení dodávky    310
8962           informace dle    296
993               o zahájení    280
410          zahájení řízení    274
122                      p č    274
93        elektrické energie    274
92        dodávky elektrické    269
602            místní úpravy    266
1833      poskytnutí účelové    237
11462         kroměříž odbor    236
1454             o přerušení    235
601         stanovení místní    235
28                  rok 2024    228
37310          český krumlov    225
3673               s smlouva    218
3080                     č p    214
331                      č 1    209
552       vyhláška stanovení    197
2033               smlouva č    193
22                    za rok    189
769             rozhodnutí o    189
1835       investiční dotace    188
9008    dotace veřejnoprávní    186
42043            český těšín    184
7358                  ze dne    182

In [114]:
themes = [
    # Trendy v dotacích a financování:
    'poskytnutí dotace',
    'investiční dotace',
    # Legislativní a právní záležitosti:
    'veřejnoprávní smlouva',
    '106/1999',
    # Městské plánování a infrastruktura:
    "úpravy provozu",
    "přechodné úpravy",
    'místní úpravy',
    # Veřejné oznámení a vyhlášky:
    'veřejná vyhláška',
    'dražební vyhláška',
    'opatření obecné povahy',
    # Energetika a služby:
    "dodávky elektrické energie"
]

result_data = pd.DataFrame()

for city in data['město'].unique():
    city_data = data[data['město'] == city].copy()
    
    for theme in themes:
        city_data[theme] = city_data['nazev'].str.contains(theme, case=False, na=False).astype(int)
    
    grouped_city_data = city_data.groupby(['město', 'rok'])[themes].sum().reset_index()
    
    result_data = pd.concat([result_data, grouped_city_data], ignore_index=True)
    
result_data

,město,rok,poskytnutí dotace,investiční dotace,veřejnoprávní smlouva,106/1999,úpravy provozu,přechodné úpravy,místní úpravy,veřejná vyhláška,dražební vyhláška,opatření obecné povahy,dodávky elektrické energie
0,Bohumín,2021,0,0,0,0,0,0,0,0,0,0,0
1,Bohumín,2023,0,0,0,0,0,0,0,0,0,0,0
2,Bohumín,2024,0,0,0,0,0,0,0,1,1,0,2
3,Boskovice,2019,0,0,0,0,0,0,0,1,0,1,0
4,Boskovice,2021,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
355,Židlochovice,2020,0,0,0,0,0,0,0,1,0,0,0
356,Židlochovice,2021,0,0,0,0,0,0,0,0,0,0,0
357,Židlochovice,2022,0,0,3,0,0,0,0,0,0,0,0
358,Židlochovice,2023,0,0,0,0,0,0,0,0,0,0,0
359,Židlochovice,2024,0,0,0,0,7,4,3,9,0,6,0

In [117]:
result_data['106/1999'].sum()

378

# pie graph

In [118]:
# df = pd.DataFrame()
# for tema in themes:
vys = result_data.groupby('město', as_index = False).sum()
del vys["rok"]

In [127]:
vys

,City,poskytnutí dotace,investiční dotace,veřejnoprávní smlouva,106/1999,úpravy provozu,přechodné úpravy,místní úpravy,veřejná vyhláška,dražební vyhláška,opatření obecné povahy,dodávky elektrické energie
0,Bohumín,0,0,0,0,0,0,0,1,1,0,2
1,Boskovice,0,0,0,0,0,0,0,12,3,13,0
2,Brno,12,140,0,0,14,3,15,71,17,6,4
3,Bruntál,0,0,0,0,6,6,0,0,2,0,0
4,Bílina,0,61,0,0,0,0,0,0,4,6,0
5,Domažlice,1,0,0,0,5,5,0,4,1,2,1
6,Dvůr Králové Nad Labem,0,0,0,1,7,1,6,3,4,4,0
7,Frýdlant Nad Ostravicí,2,0,2,0,0,0,0,2,0,0,0
8,Hlučín,0,0,0,0,0,0,0,4,0,0,0
9,Hradec Králové,37,0,1,0,1,46,6,2,8,0,20
10,Jablonec Nad Nisou,0,0,0,0,67,61,5,58,3,70,7
11,Jablunkov,7,0,13,0,1,1,0,4,1,1,0
12,Jičín,0,0,0,6,0,0,0,3,6,0,0
13,Karlovy Vary,0,0,0,0,2,2,0,29,5,24,0
14,Kladno,0,0,0,0,0,0,0,5,2,0,0
15,Kopřivnice,0,0,0,0,6,6,0,10,1,6,2
16,Krnov,0,0,0,0,11,7,4,6,4,2,2
17,Kroměříž,0,0,0,0,139,69,56,231,25,0,33
18,Kutná Hora,17,0,17,0,15,18,0,0,8,1,0
19,Lanškroun,37,1,23,1,5,5,0,1,0,6,6
20,Liberec,0,0,0,0,0,0,0,0,4,0,0
21,Litoměřice,2,0,29,352,5,22,6,1,0,0,0
22,Litvínov,0,71,104,0,13,12,1,1,4,1,0
23,Louny,1,0,1,0,10,4,6,21,1,8,1
24,Lovosice,0,0,0,0,2,2,0,0,3,0,0
25,Mělník,0,0,5,0,2,2,0,18,3,7,4
26,Nový Jičín,0,0,0,0,8,7,1,0,7,8,0
27,Nymburk,0,0,0,0,5,3,1,2,2,6,2
28,Odolena Voda,0,0,0,0,0,0,0,3,0,0,1
29,Olomouc,0,0,0,0,0,0,0,12,20,1,6
30,Orlová,0,0,3,0,0,0,0,6,3,0,2
31,Ostrava,0,11,52,0,0,0,0,29,12,15,0
32,Pardubice,1,0,0,17,1,27,8,4,13,0,4
33,Plzeň,0,0,0,0,0,0,0,0,0,0,0
34,Poděbrady,1,1,3,0,0,0,0,0,0,15,0
35,Praha,47,0,48,0,56,40,17,74,46,20,1
36,Prostějov,188,0,0,0,15,7,8,8,10,6,10
37,Písek,0,0,0,0,10,9,0,2,0,0,2
38,Rudná,0,0,0,0,0,0,0,1,0,2,2
39,Rumburk,7,2,2,0,0,0,0,2,9,0,0
40,Semily,0,0,0,0,10,10,0,1,1,1,0
41,Slaný,0,0,0,0,0,0,0,31,3,1,0
42,Strakonice,0,0,0,0,14,12,7,2,6,1,3
43,Teplice,8,0,0,0,32,26,6,1,3,44,0
44,Turnov,142,0,0,0,4,4,0,0,0,5,0
45,Tábor,0,0,0,0,26,22,4,32,8,6,3
46,Třebíč,0,0,0,1,10,7,3,37,2,3,0
47,Uherské Hradiště,58,0,110,0,5,3,2,6,6,7,6
48,Valašské Meziříčí,0,0,4,0,0,0,0,4,5,1,1
49,Varnsdorf,0,0,0,0,0,0,0,1,1,3,0
50,Zlín,0,0,0,0,24,13,11,6,10,2,0
51,Čelákovice,103,0,0,0,0,0,0,8,0,1,0
52,Česká Lípa,0,0,0,0,8,12,2,2,2,2,11
53,České Budějovice,0,0,0,0,40,38,7,2,6,4,23
54,Český Krumlov,238,5,10,0,369,311,65,19,63,14,110
55,Český Těšín,95,0,85,0,8,7,1,10,0,7,0
56,Říčany,0,0,0,0,0,0,0,1,3,0,0
57,Šlapanice,9,0,16,0,14,9,5,24,4,1,0
58,Šumperk,215,0,255,0,0,0,0,0,4,18,0
59,Židlochovice,0,0,3,0,7,4,3,10,0,6,0

In [128]:
vys = vys.rename(columns={'město': 'City'})

In [129]:
vys.head()

,City,poskytnutí dotace,investiční dotace,veřejnoprávní smlouva,106/1999,úpravy provozu,přechodné úpravy,místní úpravy,veřejná vyhláška,dražební vyhláška,opatření obecné povahy,dodávky elektrické energie
0,Bohumín,0,0,0,0,0,0,0,1,1,0,2
1,Boskovice,0,0,0,0,0,0,0,12,3,13,0
2,Brno,12,140,0,0,14,3,15,71,17,6,4
3,Bruntál,0,0,0,0,6,6,0,0,2,0,0
4,Bílina,0,61,0,0,0,0,0,0,4,6,0

In [130]:
vys.to_csv('result.csv')

In [123]:
categories = vys.columns[1:]
categories

Index(['poskytnutí dotace', 'investiční dotace', 'veřejnoprávní smlouva',
       '106/1999', 'úpravy provozu', 'přechodné úpravy', 'místní úpravy',
       'veřejná vyhláška', 'dražební vyhláška', 'opatření obecné povahy',
       'dodávky elektrické energie'],
      dtype='object')

In [124]:
result_data.to_csv('result.csv')

# Linejni graph

In [125]:
lin_g = result_data.groupby('rok', as_index = False).sum()
del lin_g['město']
lin_g.head()

,rok,poskytnutí dotace,investiční dotace,veřejnoprávní smlouva,106/1999,úpravy provozu,přechodné úpravy,místní úpravy,veřejná vyhláška,dražební vyhláška,opatření obecné povahy,dodávky elektrické energie
0,1970,0,0,0,0,0,0,0,0,0,0,0
1,2006,0,0,0,0,0,0,0,0,0,0,0
2,2008,0,0,0,0,0,0,0,2,0,0,0
3,2009,0,0,0,0,0,0,0,4,7,0,0
4,2010,0,0,0,0,0,0,0,19,3,0,0

In [126]:
lin_g.to_csv("lin_graph.csv")